language: android

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
before_install:
    - yes | sdkmanager "platforms;android-27"
jdk:
    - oraclejdk8
script:
    - ./gradlew clean build
before_install:
 - chmod +x gradlew
